language: c

sudo: required
dist: bionic

git:
  depth: 1500

compiler:
  - gcc-10

env:
  - MAKE_CHECK="root"

stages:
  - name: Coverity
    if: type = cron
  - name: Test
    if: type != cron

jobs:
  include:
    # test old Ubuntu 12.04 and OSX for compatibility
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      env: MAKE_CHECK="root"

before_install:
  # print some host info
  - env | grep -v "encrypted" | LC_ALL=C sort
  # workaround travis-ci issue #5301
  - unset PYTHON_CFLAGS

install:
  - source ./.travis-functions.sh
  - travis_install_script

before_script:
  - travis_before_script

script:
  - travis_script

after_script:
  - travis_after_script

